export type { MenuProps, MenuInstance } from './menu/types'
export type { MenuItemProps, MenuItemInstance } from './menu-item/types'
export type { MenuGroupProps, MenuGroupInstance } from './menu-group/types'
export type { SubMenuProps, SubMenuInstance } from './sub-menu/types'

export { default as IxMenu } from './menu/Menu.vue'
export { default as IxMenuItem } from './menu-item/MenuItem.vue'
export { default as IxMenuDivider } from './menu-divider/MenuDivider.vue'
export { default as IxMenuGroup } from './menu-group/MenuGroup.vue'
export { default as IxSubMenu } from './sub-menu/SubMenu'
